# Generated by Django 5.1.4 on 2025-01-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_created_at_alter_product_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmetainformation",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.DeleteModel(
            name="ProductMetaInformation",
        ),
    ]
